gpu: false
data_dir: ""
save: true
save_freq: 1000
load: false
load_dir: "./logdir/[env]/BTRL-[name]/[seed]/checkpoints/[timestep]/"
visual: False


algorithm:
  name: BTRL
  reward_prior: 1e-1
  transition_prior: 1e-3
  update_freq: 1e1
  warmup_length: 1e1
  warmup_freq: 1e1
  policy_noise: 0.0
  n_samples: 1
  temp: 1e-4

experiment:
  suite: bsuite
  env: "5"
  test: true
  steps: 1e5
  time_limit: 2000
  test_freq: 1e2
  name: "DeepSea-100"
  seed: None

replay:
  capacity: 1e3
  batch_size: 100
  sequence_length: 10

transition:
  obs_type: "grid"
  training_iterations: 100
  hidden_dim: 100
  learning_rate: 1e-3
  window_length: 3
  context_length: 1
  num_encoder_layers: 2
  heads: 4
  forward_expansion: 2
  p_seq: 0.2
  p_attn: 0.05

value:
  training_iterations: 100
  hidden_dim: 100
  learning_rate: 1e-3
  target_update_freq: 4
  discount: 0.99

terminal:
  training_iterations: 100
  hidden_dim: 100
  learning_rate: 1e-3



